name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
  
  build:
    name: Nextcloud ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        include:
          
          - version: 19.0.1
            tag: latest, 19.0.1
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1          
          - version: 19.0.0
            tag: 19.0.0
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          
          - version: 18.0.6
            tag: 18.0.6
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.5
            tag: 18.0.5
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.4
            tag: 18.0.4
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.3
            tag: 18.0.3
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.1
            tag: 18.0.1
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          
          - version: 17.0.3
            tag: 17.0.3
            locales: 2.28-10
            tzdata: 2020a-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1            
          
    steps:
      - uses: actions/checkout@v1
      
      - uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: "1"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: thost96/nextcloud
          tags: ${{ matrix.tag }}
          build_args: BASEIMAGE=nextcloud:${{matrix.tag}},LOCALES_VERSION=${{matrix.locales}},TZDATA_VERSION=${{matrix.tzdata}},NANO_VERSION=${{matrix.nano}},CURL_VERSION=${{matrix.curl}}

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1
      - uses: brpaz/hadolint-action@master
  
  securitycheck:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     needs: build
     strategy:
      fail-fast: false
      matrix:
        tags: [latest, 19.0.1, 19.0.0]
     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tags }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            image: ${{secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tags }}
            token: ${{ secrets.GITHUB_TOKEN }}
  
  security:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, 19.0.1, 19.0.0]
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USERNAME }}/nextcloud:${{matrix.tag}}
            args: --severity-threshold=high
