name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
      
jobs:
  
  build:
    name: Nextcloud ${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:   
        tag: [latest,21.0.1,21.0.0,20.0.9,20.0.8,20.0.7,20.0.6,20.0.5,20.0.4,20.0.3,20.0.2,20.0.1,20.0.0,19.0.10,19.0.9,19.0.8,19.0.7,19.0.6,19.0.5,19.0.4,19.0.3,19.0.2,19.0.1,19.0.0,18.0.6,18.0.5,18.0.4,18.0.3,18.0.1,17.0.3]
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Image Build
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tag }}      
            build-args: |
              TAG=${{matrix.tag}}