name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
  
  build:
    name: Nextcloud ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        include:
          
          - version: 20.0.4
            tag: latest
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
          
          - version: 20.0.4
            tag: 20.0.4
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
          - version: 20.0.3
            tag: 20.0.3
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
          - version: 20.0.2
            tag: 20.0.2
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
          - version: 20.0.1
            tag: 20.0.1
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
          - version: 20.0.0
            tag: 20.0.0
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1 
              
          - version: 19.0.4
            tag: 19.0.4
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 19.0.3
            tag: 19.0.3
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 19.0.2
            tag: 19.0.2
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1     
          - version: 19.0.1
            tag: 19.0.1
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1          
          - version: 19.0.0
            tag: 19.0.0
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          
          - version: 18.0.6
            tag: 18.0.6
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.5
            tag: 18.0.5
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.4
            tag: 18.0.4
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.3
            tag: 18.0.3
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          - version: 18.0.1
            tag: 18.0.1
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1
          
          - version: 17.0.3
            tag: 17.0.3
            locales: 2.28-10
            tzdata: 2020d-0+deb10u1
            nano: 3.2-3
            curl: 7.64.0-4+deb10u1            
          
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Docker Image Build
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: thost96/nextcloud:${{ matrix.tag }}      
            build-args: |
              TAG=${{matrix.version}}
              LOCALES_VERSION=${{matrix.locales}}
              TZDATA_VERSION=${{matrix.tzdata}}
              NANO_VERSION=${{matrix.nano}}
              CURL_VERSION=${{matrix.curl}} 
