name: Security Checks

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
    
  trivy:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tags: [latest, 19.0.1, 19.0.0]
     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tags }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            issue: false
            image: ${{secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tags }}
            token: ${{ secrets.GITHUB_TOKEN }}
  
  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, 19.0.1, 19.0.0]
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USERNAME }}/nextcloud:${{matrix.tag}}
            args: --severity-threshold=high
