name: Security Checks

on:
  push:
    paths-ignore: 
      - "README.md"
      - ".github/**"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"      

jobs:
    
  trivy:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tag: [latest,20.0.7,20.0.6,20.0.5,20.0.4,20.0.3,20.0.2,20.0.1,20.0.0,19.0.4,19.0.3,19.0.2,19.0.1,19.0.0,18.0.6,18.0.5,18.0.4,18.0.3,18.0.1,17.0.3]
     steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}    
        
        - name: Pull docker image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tag }}
        
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            issue: false
            image: ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tag }}
            token: ${{ secrets.GITHUB_TOKEN }}
  
  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest,20.0.7,20.0.6,20.0.5,20.0.4,20.0.3,20.0.2,20.0.1,20.0.0,19.0.4,19.0.3,19.0.2,19.0.1,19.0.0,18.0.6,18.0.5,18.0.4,18.0.3,18.0.1,17.0.3]
    steps:
        - uses: actions/checkout@master

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{ secrets.DOCKER_USERNAME }}/nextcloud:${{ matrix.tag }}
            args: --severity-threshold=high